config:
  notNotify: false
  commandWait: 2
  chatWait: 2
  chatLengthLimit: 32
  chatLimit: 8
  useRemote: false
  log: false
  dirtyList:
  - '你妈'
  - 'cao'
  commandWhiteList:
  - '/spam'
  - '/l'
  - '/login'
  - '/r'
  - '/register'
debug: false
