name: AntiSpam
version: ${project.version}
main: com.mengcraft.antispam.AntiSpam

permissions:
  spam.bypass:
    default: false
  spam.admin:
    description: Operator permission.
    default: op

commands:
  spam:
    permission: spam.admin
    description: Operator command for this plug-in.

softdepend: [SimpleORM]
